### ISSUE TITLE
npm install breaks down

### ISSUE THREAD

**Issue by adamchenwei** [fullstackreact/google-maps-react#11]
Hi, great repo! Just not sure why its not allowing me to npm install?

Any thought? I cloned the repo on my machine with node and npm installed as well as webpack
![error](https://cloud.githubusercontent.com/assets/4201698/17487848/a8a9ede8-5d64-11e6-88f0-d628f0fdc221.JPG)

**Comment by auser** [comment]
Did you run `npm publish` or `npm install`? It shouldn't try to run the republish command...

**Comment by adamchenwei** [comment]
Hi @auser  I did pretty sure nom install

**Comment by adamchenwei** [comment]
*npm

**Comment by Aourin** [comment]
Normally installs for me. Not sure what that is about without more detail. I'm using node v4.4.3 and npm v3.9.5 so it really shouldn't be much of a diff.

**Comment by auser** [comment]
This should be fixed with the latest push. 

Details: 
`prepublish` runs with `npm install` (reference: [https://docs.npmjs.com/misc/scripts](https://docs.npmjs.com/misc/scripts))
