### ISSUE TITLE
Trivial Documentation Enhancement

### ISSUE THREAD

**Issue by Aourin** [fullstackreact/google-maps-react#12]
Might seem small, but clearly lining out the exports might make entry a little easier (especially if NOT coming from the blog post). It could be as easy as just example code 
```js
import { Map } from 'google-maps-react';
```

I get laying them out as 'the components included', but then something like 

```js
import { GoogleApiWrapper } from 'GoogleMapsReactComponent'

// ...

export class Container extends React.Component {}

export default GoogleApiWrapper({
  apiKey: __GAPI_KEY__
})(Container)
```

might get a little confusing since it doesn't reference the repo itself.

**Comment by auser** [comment]
Ah, @Aourin Wanna take a shot at sending a PR with your proposed updates to the README.md?

**Comment by Aourin** [comment]
sure

**Comment by auser** [comment]
bump ^^
