### ISSUE TITLE
YOUR_GOOGLE_API_KEY_GOES_HERE won't work

### ISSUE THREAD

**Issue by EwaMakowska** [fullstackreact/google-maps-react#125]
When I try use my api_key:
`export default GoogleApiWrapper({
    apiKey: AI_and_some_numbers_and_letters
})(MapContainer)`

 I have in console that error

> Uncaught ReferenceError: AI_and_some_numbers_and_letters is not defined

I know, I did something wrong, but I can't find specyfic, adequate hoe to do it. 

Please, help.

**Comment by Eschon** [comment]
Your api key needs to be a string.  
Try `export default GoogleApiWrapper({ apiKey: 'AI_and_some_numbers_and_letters' })(MapContainer)`
