### ISSUE TITLE
Error building project 

### ISSUE THREAD

**Issue by yeion7** [fullstackreact/google-maps-react#131]
I try to build a project with Next.js, but trow a error

```
 Error: ./~/google-maps-react/dist/components/InfoWindow.js

Module not found: Error: Can't resolve 'react-dom/server' in '.../node_modules/google-maps-react/dist/components'
```

i use `"google-maps-react": "1.1.0"` and `"next": "2.4.9"`

any idea?

**Comment by auser** [comment]
Think you can throw an example project up so I can help debug?

**Comment by danielsiwiec** [comment]
Same problem here. Using `"next": "^5.0.0"`
