### ISSUE TITLE
Update dependencies to support React v16.0

### ISSUE THREAD

**Issue by luish** [fullstackreact/google-maps-react#132]
https://reactjs.org/blog/2017/09/26/react-v16.0.html

[enzyme](https://github.com/airbnb/enzyme) might be the tricky one here:
- https://github.com/airbnb/enzyme/blob/master/CHANGELOG.md#breaking-changes
- https://github.com/airbnb/enzyme/blob/master/docs/guides/migration-from-2-to-3.md

**Comment by ninahaack** [comment]
It's working fine for me. I'm using react 16. Do you know the problems that could happen?

**Comment by martinmacko47** [comment]
Any progress on updating `google-maps-react` for React v16? Currently the package has a peer dependency: `"react": "~0.14.8 || ^15.0.0",` So we can't update to React v16 if using it.
