### ISSUE TITLE
Element type is invalid problem

### ISSUE THREAD

**Issue by accateo** [fullstackreact/google-maps-react#14]
Hi, 
I have installed your package via command line. I put these lines:

`<Marker onClick={this.onMarkerClick}
          name={'Current location'} />
<InfoWindow onClose={this.onInfoWindowClose}>
      <div>
        <h1></h1>
      </div>
  </InfoWindow>
</Map>`

in my render function, but I have this error:

> Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object

Why? Obviously I have declared:

`var Map = require('google-maps-react');
var Marker = Map.Marker;
var InfoWindow = Map.InfoWindow;`

**Comment by auser** [comment]
Oh, you should be able to include them in ES6 manner:

```javascript
import Map, { Marker, InfoWindow } from 'google-maps-react'
```
