### ISSUE TITLE
Unclear usage of navigator

### ISSUE THREAD

**Issue by gDelgado14** [fullstackreact/google-maps-react#15]
Hello, 

I am just curious about the `navigator` variable in `src/index.js`. How is  this defined / what is the purpose of the entire `if` block referencing `navigator` ? 

https://github.com/fullstackreact/google-maps-react/blob/master/src/index.js#L46

Thanks!

**Comment by auser** [comment]
The `navigator` references `window.navigator`, which is exposed via updated browsers 

Ref: [https://developer.mozilla.org/en-US/docs/Web/API/Navigator](https://developer.mozilla.org/en-US/docs/Web/API/Navigator)
