### ISSUE TITLE
Is there a resize event that can be used

### ISSUE THREAD

**Issue by moraleslos** [fullstackreact/google-maps-react#151]
If the div containing the map is resized, is there a way to catch a resize event in order to recenter the marker / map appropriately?  Something similar to this:  [https://codepen.io/alexgill/pen/NqjMma](url).  Documentation doesn't seem to show anything related to a map resize.

**Comment by auser** [comment]
@moraleslos I added an example in the examples directory about how to handle this. Hope it helps!
