### ISSUE TITLE
Wrap GoogleApiWrapper with react-redux's connect

### ISSUE THREAD

**Issue by ranleung** [fullstackreact/google-maps-react#16]
Hello,

How would i wrap the GoogleApiWrapper with react-redux's connect?

I would imagine I have to have wrap export GoogleApiWrapper with the connect's mapStateToProps and mapDispatchToProps.  Like so:

```
export default GoogleApiWrapper({
  apiKey: __APIKEY___
}, mapStateToProps, mapDispatchToProps)(Container)

```

But it is not working.  Do I have to change how the GoogleApiWrapper's exports? Anyone can point me to the right direction? @auser 

Thanks!

**Comment by auser** [comment]
Hey @ranleung 

Yeah, you should wrap the `Container`, not the export, i.e.:

```javascript
const WrappedContainer = GoogleApiWrapper({
   apiKey: __APIKEY___
})(Container);
export default WrappedContainer
```

**Comment by ranleung** [comment]
awesome!! thank you! :)

closing...

**Comment by javierlecca** [comment]
Hi ranleung, 
I have the same trouble,
Could you tell me how can i set mapDispatchToProps with GoogleApiWrapper?
Please, help me.
