### ISSUE TITLE
Using http://maps.google.cn/maps/api/js instead of https://maps.googleapis.com/maps/api/js

### ISSUE THREAD

**Issue by blackhuman** [fullstackreact/google-maps-react#164]
Are there any chances to use a special URL of Google API instead of the default one? 

I found a description in [README](https://github.com/fullstackreact/google-maps-react#manually-loading-the-google-api). Could I solve my problems through this method?

reference: https://developers.google.com/maps/documentation/javascript/tutorial#https-or-http

**Comment by auser** [comment]
Wanna make a PR?

**Comment by blackhuman** [comment]
Could I just change https://github.com/fullstackreact/google-maps-react/blob/master/src/lib/GoogleApi.js#L12

from `const URL = 'https://maps.googleapis.com/maps/api/js';` 
to `const URL = opts.url || 'https://maps.googleapis.com/maps/api/js';`

**Comment by auser** [comment]
Should work!
		
		

		Get Outlook for iOS
	




On Wed, Mar 21, 2018 at 11:03 PM -0400, "blackhuman" <notifications@github.com> wrote:












Could I just change https://github.com/fullstackreact/google-maps-react/blob/master/src/lib/GoogleApi.js#L12


from const URL = 'https://maps.googleapis.com/maps/api/js';

to const URL = opts.url || 'https://maps.googleapis.com/maps/api/js';

**Comment by blackhuman** [comment]
https://github.com/fullstackreact/google-maps-react/pull/165

**Comment by auser** [comment]
I don't have tests here... perhaps we should add them. 

Feel free to add an example in the `examples/` folder.
