### ISSUE TITLE
How to import GoogleApiComponent?

### ISSUE THREAD

**Issue by batjko** [fullstackreact/google-maps-react#18]
Hi there,
I've just started with React and am reading through the blog post where this package is used.

The article says we can simply install this package and then use the GoogleApiComponent in our Map Container. But none of the code snippets in the article or in this package show how this function is actually imported.

This is what I am trying:

```jsx
import {GoogleApiComponent} from 'google-maps-react'

// [...] container class "MapContainer" declared here

export default GoogleApiComponent({
  apikey: 'blabla'
})(MapContainer)
```

This container is then imported in my main app like this:

```jsx
import MapContainer from './containers/MapContainer'

// [...]
```

But the browser console keeps complaining with 
`Uncaught TypeError: (0 , _googleMapsReact.GoogleApiComponent) is not a function`, pointing at the line where I export the GoogleApiComponent.

I'm sure I am importing that function wrong, but it's not explained anywhere?

**Comment by auser** [comment]
Ah, yes... It should be `import {GoogleApiWrapper} from 'google-maps-react'`, not `GoogleApiComponent`

**Comment by batjko** [comment]
Ah. just saw that on the package's Readme, too. It's just different from the article.
No worries.

**Comment by gpnoel** [comment]
The README still says `import {GoogleApiWrapper} from 'GoogleMapsReactComponent'`

**Comment by afroguy16** [comment]
The docs didn't do justice at all
