### ISSUE TITLE
(0 , _googleMapsReact.GoogleApiWrapper) is not a function

### ISSUE THREAD

**Issue by gersongams** [fullstackreact/google-maps-react#181]
Hi I'm using gatsby and netlify-CMS for a project, and I'm having some issues when I build the project, it works fine on local but on production, it gives me this error

```
WebpackError: (0 , _googleMapsReact.GoogleApiWrapper) is not a function
```

And I see in the examples you put:

```
const GoogleApiWrapper = __IS_DEV__
  ? require('../src/index').GoogleApiWrapper
  : require('../dist').GoogleApiWrapper;
```
Maybe is loading the wrong function in production? :cry: please help!

**Comment by auser** [comment]
Please make a [https://codesandbox.io/](https://codesandbox.io/) to demonstrate your error.

Thanks!

**Comment by 3dworldBangalore** [comment]
https://codesandbox.io/s/03k60n3zp0
@auser

**Comment by 0xpulsar** [comment]
@auser 
https://codesandbox.io/s/3qmr7zwzkp

**Comment by camergardi** [comment]
Your using 'google-map-react' when this is 'google-maps-react' npm install google-maps-react and change your import to the correct name and it should work
