### ISSUE TITLE
PolyLine center and zoom

### ISSUE THREAD

**Issue by aniov** [fullstackreact/google-maps-react#183]
How can I center and zoom to fit a polyline in google maps window?

/*I receive 'polyLine' from Strava as props and set it in state*/

`render() {

       let finalPolyLine = polylineEncoder.decode(this.state.polyLine);/*transform to google coords*/
       let bounds = new window.google.maps.LatLngBounds();

       finalPolyLine.map((point) => {
           const position = new google.maps.LatLng(point.lat, point.lng);
           bounds.extend(position );
       });

        return (
                <Map 
                     google={this.props.google}
                     zoom={16} /*need to set the zoom so the polyline will fit*/
                     initialCenter={finalPolyLine[Math.round(finalPolyLine.length / 2)]} /*need to center*/
                >
                    <Polyline
                        path={finalPolyLine}
                        strokeColor="#f669c5"
                        strokeOpacity={0.9}
                        strokeWeight={3}/>                
                </Map>
        );
    }
}`

**Comment by arbass22** [comment]
Hey @aniov I am working on fix for this, since I needed this as well

**Comment by arbass22** [comment]
pull request #205
