### ISSUE TITLE
Can I pass a Component to InfoWindow?

### ISSUE THREAD

**Issue by bos-hieu** [fullstackreact/google-maps-react#185]
I can not pass my component like children to InfoWindow because it required a element for children, not Node. Can you update this?

**Comment by dzmitrypanamarenka** [comment]
I have similar issue. I can't mount Component inside InfoWindow and pass state to it via redux because it can't recognize store. If I mount it inside a Map - everything is ok.

**Comment by andreykul** [comment]
@dzmitrypanamarenka The redux issue is due to change in context. It can be easily fixed by wrapping your Component with a `Provider`. 

The issue I'm having is that you cannot do any action on the InfoWindow, it is all rendered from a String thus losing all event bindings :(

**Comment by lepirlouit** [comment]
Same issue with react-intl, unable to use a react-intl component.

**Comment by janhoeck** [comment]
This fixed my issue too. Thank you!
