### ISSUE TITLE
is there any chance to get current latlng when use " centerAroundCurrentLocation:true"

### ISSUE THREAD

**Issue by swaitw** [fullstackreact/google-maps-react#188]
i tried to use " centerAroundCurrentLocation:true" to use the users current location as the center of map. i also want to make a marker to show users current location but i dont know how can get the latlng to set the marker is any one can help? thanks a lot.

**Comment by swaitw** [comment]
i fixed by my self thanks

**Comment by timmoti** [comment]
@swaitw Could you kindly explain how you did it? I'm trying to set a marker on the current location which is stored as a state within the Map component but am struggling to figure out how to access it in my Marker component

**Comment by daiky00** [comment]
@swaitw I have the same situation can you post the answer please!
