### ISSUE TITLE
Adding Marker Label using default google value

### ISSUE THREAD

**Issue by rullymartanto** [fullstackreact/google-maps-react#210]
google maps marker label usually using this

 var marker = new google.maps.Marker({
          position: location,
          label: labels[labelIndex++ % labels.length],
          map: map
        });

Can we add label maker similar like that ?

Thanks

**Comment by rullymartanto** [comment]
that is sample from google maps api.. but never mind I have solve this issue
Thanks

**Comment by auser** [comment]
How did you solve it (for future users)?

**Comment by eladmoshe** [comment]
OK, I wasn't able to find it in the documentation, but in case someone needs it, this works:
```
<Marker label="BB"/>
```
![image](https://user-images.githubusercontent.com/1702227/41971451-263ee4e0-7a17-11e8-82c9-79a94f6f1e1b.png)
