### ISSUE TITLE
I want to create a double click trigger function in markers

### ISSUE THREAD

**Issue by thomvilla** [fullstackreact/google-maps-react#211]
Hi, i am starting with react js and in want know how is possible create a double click trigger in markers, now i have onClick={} y  onMouseover={} in markers. But i need DblClick={} or RighClick={}. Thanks!!

**Comment by mrh2v** [comment]
@thomvilla  . You can listen event on map, using onDblclick={}, onRightclick={} and 
some other events ...

' ready',
  'click',
  'dragend',
  'recenter',
  'bounds_changed',
  'center_changed',
  'dblclick',
  'dragstart',
  'heading_change',
  'idle',
  'maptypeid_changed',
  'mousemove',
  'mouseout',
  'mouseover',
  'projection_changed',
  'resize',
  'rightclick',
  'tilesloaded',
  'tilt_changed',
  'zoom_changed'
