### ISSUE TITLE
Unable to successfully loop in array and use the InfoWindow component (Beginner)

### ISSUE THREAD

**Issue by sgouver** [fullstackreact/google-maps-react#244]
Hello,

Thank you for your great library.

I am trying to embed an array inside a Google Map.

All the markers appeared correctly but when I added the `<InfoWindow />` component directly I received the error : 

> _djacent JSX elements must be wrapped in an enclosing tag_

 then I wrapped them inside a `<div>` but a new error appeared 

> _React does not recognize the `mapCenter` prop_ 

Is there any way to make it work ?

```
{
          wonders.filter(wonder => wonder.age === 'New')
          .map( wonder => (
          <div  key = {wonder.location.lat}>
            <Marker
              key = {wonder.location.lat}
              onClick={this.onMarkerClick}
              title={wonder.name}
              name={wonder.name}
              icon={{
                  url: wonder.image,
                  scaledSize: new google.maps.Size(50,50)
                }}
              position={
                {lat: wonder.location.lat,
                 lng: wonder.location.lng}
               }/>
             <InfoWindow
               marker={activeMarker}
               visible={showingInfoWindow}>
                 <span>
                   <h1>{wonder.name}</h1>
                 </span>
             </InfoWindow>
           </div>
            )
           )
         }

```

**Comment by tusho** [comment]
Why was this closed? I have the same question. Mapping through this would be the first thing to do (who wants to just show one marker)? but there seems to be no easy way as InfoWindow seems needing to be global!?
