### ISSUE TITLE
Cancel any pending requests if component is unmounted

### ISSUE THREAD

**Issue by OsamaShabrez** [fullstackreact/google-maps-react#248]
> Can't call setState (or forceUpdate) on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method

If you quickly switch between different components and Map is still loading, react complains of memory leak.

We need something similar to [axios pending request cancelation](https://github.com/axios/axios#cancellation) in this library to cancel all pending requests and gracefully let the component unmount.

**Comment by afuller611-animas** [comment]
@OsamaShabrez Did you ever resolve this issue?
I have the same problem.

**Comment by OsamaShabrez** [comment]
@afuller611-animas no, I used this library in a small project for some prototyping and never got back to it. Generally, if nothing else works, a state can be kept as a class field which can be queried before calling setState. A very quick dirty code:

``` javascript
class MyClass extends Component {
  isMounted = false;

  componentDidMount() { isMounted = true; }
  componentWillUnmount() { isMounted = false; }
}
```
query this field before calling setState.

**Comment by afuller611-animas** [comment]
Yeah, was hoping to resolve this without using that method -- but it gets the job done since I can't control this library. Thanks a ton.
