### ISSUE TITLE
How to open info window from external link.

### ISSUE THREAD

**Issue by JohPik** [fullstackreact/google-maps-react#275]
Hello everyone,

In the app I am building I have a list of markers rendering on map that I stored in array. My markers are clickable, info widow opens. 🚀🚀🚀

Then I have a side bar with a list of all my markers name. I would like the info window to open when the link is clicked. 

I want to to call onMarkerClick() from the link, but it needs two parameters,
**props** and **marker**. 

I got the **marker** , but how do I get the **props** from ??🤦🤦 

Does anyone have been facing the same issue?? Start to think I should have used another library.

Thanks guys,
J

**Comment by jackpilowsky** [comment]
You need to save the marker props in your state and then pass them to the InfoWindow. 
```
  onMarkerClick(props, marker, e) { 
    var selectedIncident = this.props.incidents.filter((incident) => {
      return incident.event_id === marker.id;
    })[0];

    // update the InfoWindow props
    this.setState({
      activeMarker: marker,
      showingInfoWindow: true,
      selectedIncident: selectedIncident
    });
  }  
```
