### ISSUE TITLE
"This page can't load Google Maps correctly" pop up box

### ISSUE THREAD

**Issue by eddydinh** [fullstackreact/google-maps-react#281]
To whom this may concern,

I tried incorporating React and Google Maps API to create my web app using your guide at: https://www.fullstackreact.com/articles/how-to-write-a-google-maps-react-component/

However, upon loading the map onto my page at localhost:3000 (I used webpack server that comes with create-react-app to host my website), the map was displayed with Google's watermark "For development purposes only."

In the console, there was an error message that said " You have exceeded your request quota for this API"

I also notice that in the article the live demonstration also encounters the same problem.

Any advice?

Thanks

Eddy

![problem](https://user-images.githubusercontent.com/36684038/48024320-37a57600-e0f5-11e8-995c-14a44e36c325.PNG)
![problem2](https://user-images.githubusercontent.com/36684038/48024321-37a57600-e0f5-11e8-8477-96250ac5ff15.PNG)

**Comment by jackpilowsky** [comment]
Its a problem with your Google Cloud Platform account. They have been making changes that basically amount to they want to make more money. Try going to the link in the console error message for more details.
