### ISSUE TITLE
adding new marker and circle on clicked lat lng

### ISSUE THREAD

**Issue by subooom** [fullstackreact/google-maps-react#283]
I am getting a `React does not recognize the `mapCenter` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `mapcenter` instead. If you accidentally passed it from a parent component, remove it from the DOM element.`
I am not even using the `mapCenter` prop on my map because `initialCenter` is working.

**Comment by jackpilowsky** [comment]
Which component are you setting the mapCenter on? Care to share some of your code?
