### ISSUE TITLE
Polygon / Circle example in npm 2.0.2 (latest?) not working

### ISSUE THREAD

**Issue by cernoel** [fullstackreact/google-maps-react#300]
Error: 'Polygon' is not defined  react/jsx-no-undef
Error: 'Circle' is not defined  react/jsx-no-undef
See example: https://github.com/fullstackreact/google-maps-react/blob/master/README.md#polyline
Do i need to import something else?

**Comment by kpl39** [comment]
I had the same problem, it looks like they haven't published the latest version (2.0.3) to npm. 

You can run `npm i fullstackreact/google-maps-react#master --save` to get v2.0.3. 

Circles and Polygons now work for me.

**Comment by cernoel** [comment]
ok, thank you very much! Can confirm, works so far!
