### ISSUE TITLE
heatmap doesn't update

### ISSUE THREAD

**Issue by ismaelaarab** [fullstackreact/google-maps-react#304]
Hi

I'm trying to update the map heatmap with realtime firebase data but it doesn't update.

this is my code:

`import React, { Component } from 'react';`
`import { Map, GoogleApiWrapper, HeatMap } from 'google-maps-react';`
`import firebase from 'firebase/app';`
`import 'firebase/database';`
`import 'firebase/auth';`

`export class MapContainer extends Component {`

  `constructor(props) {`
   ` super(props);`

`    this.state = {`
`      positions: []`
`    };`
`  }`

`  componentDidMount() {`

`    firebase.database().ref().child('accessPoints').orderByChild('apFloors').equalTo('Verdiep 1').on('value', snapshot => {`
`      let positions = [];`

 `     Object.keys(snapshot.val()).forEach(function (key) {`
 `       if (snapshot.val()[key].observations) {`
  `        snapshot.val()[key].observations.forEach(function (observation) {`
    `        if (observation.location) {`
    `          if (!isNaN(observation.location.lat) && !isNaN(observation.location.lng)) {`
     `           positions.push({ lat: observation.location.lat, lng: observation.location.lng });`
    `          }`
    `        }`
 `         });`
`        }`
`      });`

`      this.setState({`
`        positions: positions`
 `     });`

`    });`
`  }`

`  render() {`
`    return (`
`      <Map`
  `      google={this.props.google}`
 `       zoom={2}`
  `      style={{ width: '100%', height: '100%' }}`
`        containerStyle={{ width: '100%', height: '50vh', position: 'relative' }}`
 `       initialCenter={{ lat: 51.193167, lng: 4.403540 }}`
`      >`

 `       <HeatMap`
    `      opacity={1}`
  `        positions={this.state.positions}`
    `      radius={12}`
`        />`

`      </Map>`
`    );`
`  }`
`}`

`export default GoogleApiWrapper({`
`  apiKey: '',`
`  libraries: ['visualization']`
`})(MapContainer);`

**Comment by developer323** [comment]
how did you fix it ?

**Comment by flyingonionman** [comment]
I am having the same issue, can you tell me how you fixed it?

**Comment by danieloquelis** [comment]
I'm having the same issue, did you solve it?

**Comment by eduardocastelan** [comment]
Long time ago. I got it to work eventually

**Comment by jeffdico** [comment]
I had the same problem and it turns out that you have to use one instance of the heatmap for all the heatmap data that you have.  here is my example  

...
// this piece of code is from a method from my Component class 

		let heap_map_data = [], hdata; 
				
		for (var i=0; i < resp.locations.length; i++) {
			heap_map_data.push(new google.maps.LatLng(Number(resp.locations[i][0]), Number(resp.locations[i][1]) )) 
		}

		
		if (this.heatmapins[0] !== null){
			this.heatmapins[0].setData(heap_map_data);
			this.heatmapins[0].setMap(this.props.mapins);
		}
		else {
			this.heatmapins[0] = new this.props.googleins.visualization.HeatmapLayer({
			  data: heap_map_data
			});

			this.heatmapins[0].setMap(this.props.mapins);  // initialize the hear map here
		}
