### ISSUE TITLE
API key not working

### ISSUE THREAD

**Issue by SteveStrop** [fullstackreact/google-maps-react#317]
I've added my (verified working) API Key  into: 
`export default GoogleApiWrapper({
    api: API_KEY
})(GoogleMapsContainer)`

I've tried using a variable, a string and even the key you give on the blog post for the value of API_KEY but none of them work. The map is greyed out "for development only".

EDIT: I'm using chrome and the dev tools show the script tag added is:
`<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?callback=loaderCB01550089375666&amp;libraries=places&amp;v=3&amp;language=en"></script>`

from where I can see the API key has not been inserted.

What am I missing?

Thanks

**Comment by julisalis** [comment]
Hi Steve!

The api prop for GoogleApiWrapper it's "apiKey", not "api".

**Comment by SteveStrop** [comment]
Thanks
