### ISSUE TITLE
Handle more events than those defined in evtNames

### ISSUE THREAD

**Issue by prudentmildew** [fullstackreact/google-maps-react#33]
Hi,

Thank you for providing a great module!

I might be missing something obvious, but is there a way to handle other events than [the ones specified in `const evtNames`?](https://github.com/fullstackreact/google-maps-react/blob/master/src/index.js#L22)

If not, would you consider a pull request?

Thanks in advance,
Erland Wiencke

**Comment by auser** [comment]
PRs ALWAYS welcome :)
