### ISSUE TITLE
InfoWindow and Router

### ISSUE THREAD

**Issue by eur2** [fullstackreact/google-maps-react#350]
Hi, I'm trying to render markers behaving as a modal/dialog with their own route. 
The markers are clickable with the InfoWindow component and I would like to add a Route for each of them when the InfoWindow is activated. 
Each markers should have their own URL.
I Didn't find any docs about that. Anyone has an idea how to solve this?

**Comment by grdpr** [comment]
I'm trying to pass some Router component (using `reach-router`) around the InfoWindow component but it doesn't seems working like that.
