### ISSUE TITLE
Custom Map Style

### ISSUE THREAD

**Issue by AdamLee321** [fullstackreact/google-maps-react#360]
I created a custom google map style at https://mapstyle.withgoogle.com/

How do I import the the JSON styling into the Map component, other libraries use defaultOptions={}, what is the solution in this library?

Any help is greatly appreciated.

-Adam.

**Comment by php7webmob** [comment]
+1 I am also facing the same issue of importing json and passing it as style prop.

**Comment by AdamLee321** [comment]
That's a nice way then I done it, in my on ready function I called a function and in that function I passed map, then I did.

_setMapStyle(map){
    map.setOptions({
     styles: customMapStyle
    })
}

I will try your way as it is much cleaner and simpler. Thanks.

**Comment by php7webmob** [comment]
> That's a nice way then I done it, in my on ready function I called a function and in that function I passed map, then I did.
> 
> _setMapStyle(map){
> map.setOptions({
> styles: customMapStyle
> })
> }
> 
> I will try your way as it is much cleaner and simpler. Thanks.

Hey wait! My way didn't solved the problem for me. I was actually asking for help and was explaining what I did. Still stuck at applying custom styles from JSON.

**Comment by php7webmob** [comment]
Please re-open this issue.

**Comment by AdamLee321** [comment]
Sorry I read your comment wrong. I was wondering because after I posted my solution I thought I tried that already. 

Setting the custom map style has nothing to do with this library it is to do with the google maps API. 

Can you try my solution?

**Comment by php7webmob** [comment]
Sorry I did not understand your solution properly. Can you please elaborate? Like how did you solved this exactly? A little code might help. Thanks.

**Comment by AdamLee321** [comment]
Yeah sure my apologises for not being clear enough.

```
import mapStyle from '../../../../assets/map/mapStyle.json'

_setMapStyle(map) {
    map.setOptions({
      styles: mapStyle
    })
  }

<Map
            style={MAP_STYLE}
            google={this.props.google}
            zoom={this.state.zoom}
            initialCenter={this.state.center}
            onReady={(map) => this._setMapStyle(map)}
          >
              <Marker
                position={{
                  lat: trackingDetails.gpsNorth,
                  lng: trackingDetails.gpsEast
                }}
                icon={{
                  url: MAP_MARKER,
                }}
              />
            )}
          </Map>
```

And my mapStyle.json file is just the json content I have copied from [Styling Wizard: Google Maps APIs] (https://mapstyle.withgoogle.com/)

**Comment by php7webmob** [comment]
can you please verify in your `package.json` that  whether you are using `google-maps-react` or `google-map-react` . It's just that  both are different libraries and both provide different APIs. What you are suggesting me is the feature provided by google-map-react and I am using google-maps-react. Please confirm.

**Comment by AdamLee321** [comment]
![Screenshot 2019-07-19 at 11 06 10](https://user-images.githubusercontent.com/22890658/61527833-3f077800-aa15-11e9-89e1-a7371a34d385.png)

Yes I am using google-maps-react.

**Comment by php7webmob** [comment]
Got it! Thanks for everything! :) :+1:

**Comment by AdamLee321** [comment]
Is it working for you for?

**Comment by AdamLee321** [comment]
If it is working for you and you plan to make no further changes then great but if you are I would recommend creating a function like so: 

![Screenshot 2019-07-19 at 11 19 55](https://user-images.githubusercontent.com/22890658/61528620-28622080-aa17-11e9-9d99-6a7c537d6a18.png)

And use the map has loaded function to plot the source and destination points and draw the route between them, fitting the map to bounds, etc. Like so.

![Screenshot 2019-07-19 at 11 21 42](https://user-images.githubusercontent.com/22890658/61528729-6cedbc00-aa17-11e9-8146-12cd70bceb32.png)

Hope this covers everything you need to know about this library and google maps API. They are great and are used very often in projects. Glad I could help.

**Comment by php7webmob** [comment]
Thanks. :100: :+1:

**Comment by ClydSpyd** [comment]
> That's a nice way then I done it, in my on ready function I called a function and in that function I passed map, then I did.
> 
> _setMapStyle(map){
> map.setOptions({
> styles: customMapStyle
> })
> }
> 
> I will try your way as it is much cleaner and simpler. Thanks.

Thanks so much for this, Adam. I was struggling to get my styles applied for an hour or so and your answer solved the problem right away!

**Comment by AdamLee321** [comment]
Glad I could help :)

**Comment by ReangeloJ** [comment]
> Glad I could help :)

Hey Adam when I try your method I get an error saying map.setoptions is not a function. 

![image](https://user-images.githubusercontent.com/25207023/70054842-967b3e80-15d8-11ea-8b21-63caa4d204b2.png)

**Comment by ReangeloJ** [comment]
Nevermind, I found a different solution. 

Set your components defaultProps to the style that you want and add it to the styles prop.

![image](https://user-images.githubusercontent.com/25207023/70056740-41412c00-15dc-11ea-9dba-d0b2215f9720.png)
