### ISSUE TITLE
How to render over 5000 markers faster

### ISSUE THREAD

**Issue by bryan-mwas** [fullstackreact/google-maps-react#364]
Hi Guys,

I have been trying to render over 5000 points but it's quite slow especially when I implement filtering.

What's the best way to go about this?

**Comment by akif-ih** [comment]
> Hi

@bryan-mwas have u found any way of doing a rendering of 5000 marker faster.

**Comment by mustaqeem** [comment]
@akif-ih & @bryan-mwas, have you found answer for this?
