### ISSUE TITLE
There are no drag events for markers

### ISSUE THREAD

**Issue by MityaSavchenko** [fullstackreact/google-maps-react#388]
I use react with typescript and I can’t use onDragStart and onDragEnd event for markers. Only onClick and onMouseover are available. Maybe u can add it or there are some alternatives for that?

**Comment by Earle-Poole** [comment]
For those coming across this same issue.. it is because the prop should only have one capitalized letter in it's naming. Ex: onDragstart, onDragend, onContextmenu, etc...

**Comment by willydavid1** [comment]
onDragstart doesn't work for me. How did you solve it?

`<Marker
   ...
  onDragstart={() => console.log("onDragstart")}
  ....
/>`

**Comment by cordial** [comment]
Why was this closed, they still arent exposed?
