### ISSUE TITLE
Drag marker event with callback providing lat/long?

### ISSUE THREAD

**Issue by acomito** [fullstackreact/google-maps-react#39]
Is there an event for moving the Marker and getting the new lat/long info?

like [onDragEnd](https://github.com/fullstackreact/google-maps-react#ondragend) but for the marker?

**Comment by JesperWe** [comment]
No there isn't, unfortunately. Just found this issue when looking for it.

**Comment by JesperWe** [comment]
PR #43

**Comment by paradigmist** [comment]
Hi @JesperWe, can I have an example of draggable marker?

**Comment by JesperWe** [comment]
@paradigmist Just apply the PR and do something like:
``` 
<Marker position={marker.position} key={index} draggable={true} onDragEnd={props.onMarkerDragEnd}/>
```

**Comment by paradigmist** [comment]
@JesperWe The PR has been merged right? If I add `draggable` and `onDragEnd` attributes the my map marker is still unmovable, is there any I am missing?

**Comment by JesperWe** [comment]
No afaics the PR is not merged.

**Comment by auser** [comment]
PR is merged and released a new version.

**Comment by alexisspa9** [comment]
It is probabl a silly wuestion and is but i can't seem to figure out how to retirive the lat and lng after the event is fired. I passed a function on onDragEnd which is like this:

onMarkerDragEnd = (evt) => {
  console.log(evt);
}

<Marker draggable={true} onDragEnd={this.onMarkerDragEnd}/>


how do i get the marker position from the evt?

**Comment by anasyo10** [comment]
I would like to know as well, how do you get the lat lng ?

**Comment by alexisspa9** [comment]
Hi @JesperWe, I really tried to figure this out but i can't. How do you get the lat and lng of the marker after the event is being fired? I did this:

`<Marker draggable={true} onDragEnd={this.onMarkerDragEnd}/>`

and the function onMarkerDragEnd is:
`onMarkerDragEnd = (evt) => {
  console.log(evt);
}`

it logs a google maps object on which i cant figure out the way to retrieve the marker position, i tried a lot of stuff like:
`  console.log(evt.google.maps.Marker.getPosition().lat());`

but it always returns an undefined error. Help is really appreciated!

Thank you very much

**Comment by alexisspa9** [comment]
@anasyo10  I posted the question on stackoverflow and thanks to [tholle](https://stackoverflow.com/users/3617886/tholle) the answer is that:
The third argument to the onDragEnd event listener function contains the coordinates of the marker after the drag.

and i tested like this:
`onMarkerDragEnd = (one, two, three) => {
    const { latLng } = three;
    const lat = latLng.lat();
    const lng = latLng.lng();
    console.log(lat);
  };`

and it logs the lat so it works! I hope this helps you.

**Comment by anasyo10** [comment]
@alexisspa9  you are love, thanks alot.

**Comment by zomars** [comment]
Thank you @Timothylawler I was banging my head with this!

**Comment by satyasandeep007** [comment]
@alexisspa9  can you tell me what are the first two arguments in onMarkerDragEnd event?

**Comment by khushal87** [comment]
I am getting my initialCenter coordinates every time I drag the marker to get the location coordinates. Please can anyone help me out? @alexisspa9

**Comment by shivamjjha** [comment]
```
onMarkerDragEnd(mapProps, map) {
        console.log('args:', mapProps, map);
        console.log(map.getCenter().lat());
}
```
