### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by lishi500** [fullstackreact/google-maps-react#404]
Can you please publish the latest stable version to npm. This library is really good, but the current npm version is 2.0.2, which updated 2 years ago. A lot of functions is not included.

**Comment by rpc1910** [comment]
I'm having the same problem, I want to use the Circle component but it doesn't exist in version 2.0.2.
Is there a date for the release of a new version @auser ?

**Comment by srajpal1990** [comment]
UP

**Comment by douglasduartetb** [comment]
Still waiting

**Comment by auser** [comment]
Apologies for the delay. Updated
