### ISSUE TITLE
Google Maps API warning: RetiredVersion

### ISSUE THREAD

**Issue by 7s4r** [fullstackreact/google-maps-react#42]
https://developers.google.com/maps/documentation/javascript/error-messages#retired-version

Can you please update the version to 3.25?

**Comment by Szarko** [comment]
@7s4r - You can now manually specify version by passing {version: '3.25'} to the GoogleApiWrapper.  Just add the version key when you pass the apiKey key.

**Comment by 7s4r** [comment]
@Szarko Thanks :) I was thinking about a possibility to set custom version but didn't see full options list [here](https://github.com/fullstackreact/google-maps-react/blob/master/src/lib/GoogleApi.js#L4).
