### ISSUE TITLE
Can't dynamically add Markers

### ISSUE THREAD

**Issue by paulvincentphillips** [fullstackreact/google-maps-react#436]
Hi!

I want to dynamically add markers after fetching locations from Google's place api and storing them in state. 
I fetch the data, add it to state then call displayMarkers:

```
displayMarkers = () => {
    this.state.newStations.map((station, index) => {
      let lat = station.geometry.location.lat();
      let lng = station.geometry.location.lng();
      return (
        <Marker
          key={index}
          id={index}
          position={{
            lat: lat,
            lng: lng,
          }}
          onClick={() => console.log("You clicked me!")}
        />
      );
    });
  };
```
This seems like it should work. State is updated but I'm not seeing the markers I've created. Anyone have any idea why?

**Comment by paulvincentphillips** [comment]
I managed to have another look at this after work today. It seems to me that <Marker> must be a child of <Map> in order to be overlaid onto the map. 

> Marker
> To place a marker on the Map, include it as a child of the <Map /> component.

Is there any way to return the Marker as a child of <Map>? 

In the google maps API it seems as though you can do this like so: 
```
var marker = new google.maps.Marker({
    position: myLatLng,
    map: map,
    title: 'Hello World!'
  });
```

You pass in the value map, which is the map you wish your marker to be attached or overlaid onto. The prop "map" exists in google-maps-react but there doesn't seem to be a property in Marker which accepts map.

**Comment by mandy6720** [comment]
@paulvincentphillips I had the same issue 😕 

The way I handled it was to wrap the map component in another component, handling the dynamic adding of markers in the parent and pass down the marker data to the map component as props.  That way, it will trigger a re-render when props (the marker data) gets changed

**Comment by paulvincentphillips** [comment]
Thanks for that! I actually moved my project to an android project from React so I can't test your solution! I'll bear it in mind next time I use this package in future 😃

**Comment by dpoeira91** [comment]
In my case I had to use destructuring of the props in the Marker, like so:

`<Marker key={idx} position={position} {...props} icon={icon}/>`

It might be helpful to add that to an example somewhere
