### ISSUE TITLE
How do I make a polygon?

### ISSUE THREAD

**Issue by SantosOMartinez** [fullstackreact/google-maps-react#460]
I am currently trying to make a polygon so that I can shape it as the cities in my island. I do not see how I can implement the polygons. If there is no current way to implement them will there be one in the near future?

**Comment by mukhtorov** [comment]
`triangleCoords` should be your island position

`   
const triangleCoords = {
{ lat: 41.2935, lng: 69.2401}
{ lat: 41.2935, lng: 69.2401}
{ lat: 41.2935, lng: 69.2401}
}
     <Polyline
          path={triangleCoords}
          strokeColor="red"
          strokeOpacity={0.4}
          strokeWeight={1} />
`
