### ISSUE TITLE
Documentation should describe the parameters passed to Marker.onDragend

### ISSUE THREAD

**Issue by nickperkinslondon** [fullstackreact/google-maps-react#487]
Documentation should describe the parameters passed to Marker.onDragend.
The handler gets 3 complex objects, and its not easy to figure-out what they are.

**Comment by YaakovHatam** [comment]
```
   moveMarker(props, marker, e) {
        console.log(e.latLng.lat(), e.latLng.lng())
    }
```

**Comment by AntoRichard** [comment]
I don't have property name onDragend in Marker can you help me out with this?

**Comment by DonBeaaar** [comment]
@YaakovHatam 

> Hope it will help you: (it worked for me)
> 
> ```js
> <Marker
>     onDragend={this.moveMarker.bind(marker)}
> </Marker>
> ```
> 
> ```js
>    moveMarker(props, marker, e) {
>         console.log(e.latLng.lat(), e.latLng.lng()) // get the new coordinates after drag end
>     }
> ```

It was helpful !
