### ISSUE TITLE
Bug: Boolean Props set to false are not passed to the mapConfig

### ISSUE THREAD

**Issue by meaganoff** [fullstackreact/google-maps-react#50]
If you set a boolean prop to false, it gets deleted on Line 155/156:

```  
if (!mapConfig[key]) { 
    delete mapConfig[key]; 
} 
```
https://github.com/fullstackreact/google-maps-react/blob/master/src/index.js#L155

This would be fine if the defaults for these options were always false, but a lot of the UI options (such as `draggable`) default to true. So there’s pretty much no way to set them to false and actually have the option get passed to the map upon instantiation.

I can submit a PR for this— it’s a pretty simple fix (`mapConfig[key] == null`). Just wanted to flag it as a bug first.

Thanks!

**Comment by thienanle** [comment]
Issue should be closed. But this hasn't yet been published to NPM.

**Comment by auser** [comment]
Pushed `v1.1.0`. Thanks for reporting!
