### ISSUE TITLE
show Satellite tab by default

### ISSUE THREAD

**Issue by aningbo** [fullstackreact/google-maps-react#502]
I would like to have **Satellite** as the default selected tab instead of **Map**. How can I go about doing this?

<Map 
                        google={this.props.google} 
                        zoom={15} 
                        streetViewControl={false}
                        fullscreenControl={false}
                        containerStyle={{width: '100%', height: '100%'}}
                        initialCenter={{lat: 24.82419,lng: 93.96965}}
                        onClick={(e) => {
                          console.log(e);
                        }}
                      >
                      </Map>

**Comment by briantical** [comment]
`Map` has the prop **mapType**. 
```
<Map
  google={this.props.google}
  zoom={15}
  mapType='satellite' // Add this prop
  streetViewControl={false}
  fullscreenControl={false}
  containerStyle={{width: '100%', height: '100%'}}
  initialCenter={{lat: 24.82419,lng: 93.96965}}
  onClick={(e) => {
  console.log(e);
  }}
>
```

This will set the map to the satellite tab by default.

**Comment by aningbo** [comment]
Perfect.

Where did you get the documentation? I just couldn't find it earlier.

**Comment by briantical** [comment]
@aningbo there are previous issues that highlighted the issue. The prop **_mapType_** seems to be missing the types definitions.
