### ISSUE TITLE
How to add KML Layer ?

### ISSUE THREAD

**Issue by bhosalepranil16** [fullstackreact/google-maps-react#504]

**Comment by hsoljic1** [comment]
You can put component as child of Map so it gets google and map properties. In that component you can create and KmlLayer to your map. Example of component:
`
const KmzLayer = ({ map, google, kmzUrl }) => {
  const [kmzLayer, setKmzLayer] = useState(null)
  useEffect(() => {
    if(map) {
      if(kmzLayer) {
        kmzLayer.setMap()
      }
      const newKmzLayer = new google.maps.KmlLayer(kmzUrl)
      newKmzLayer.setMap(map)
      setKmzLayer(newKmzLayer)
    }
  }, [map, kmzUrl])
  return null
}
`

and in Map component:
`
<Map>
  <KmzLayer kmzUrl={urlToKmzOrKmlFile} />
`
