### ISSUE TITLE
Exposing Google Map API key

### ISSUE THREAD

**Issue by davidjeyachandran** [fullstackreact/google-maps-react#543]
This library is exposing the Google Maps API in the source of the page.
```
<script src="https://maps.googleapis.com/maps/api/js?key=API_KEY&amp;callback=..."></script>
```

The problem is found in the file `GoogleApi.js` in the `url` function. It forms a url that includes the apiKey. This exposes the key publically. I'm assuming that the key needs to be kept a secret.

**Comment by garytube** [comment]
Nope, the Google API key always publicly available.

**Comment by davidjeyachandran** [comment]
Thanks for the quick response. I asked because I got an email from Google titled "Publicly accessible Google API key for Google Cloud Platform project".
