### ISSUE TITLE
Where to Pass API Key?

### ISSUE THREAD

**Issue by askaper** [fullstackreact/google-maps-react#58]
Before I begin, please forgive me as I'm relatively new, but...

Where does one pass the API key when using this repository? I've poured over all of the the documentation both here and on Full Stack React and see nothing regarding where to actually pass one's Google Maps API Key. 

So far, the only conclusion I've come to is on line 32 of GoogleApi.js in the node modules folder where the default argument of opts.hasOwnProperty() is 'apikey'. 

If anyone could tell me if I'm close or totally wrong and why I'd be most grateful. Thanks!

**Comment by alexanderwhatley** [comment]
I would like to knonw this as well. It seems that it is somehow passed in through the this.props.google item, but I am not sure what that is, or how to use it...

**Comment by tzerb** [comment]
There is a file in the root of the project called '.env.example'.  Place your key in this file and rename to '.env'.  (I have single quotes around my key but I'm not sure if that necessary.)

**Comment by wedneyyuri** [comment]
You can see it here: https://www.fullstackreact.com/articles/how-to-write-a-google-maps-react-component/#the-map-container-component

```
export class Container extends React.Component {
  render() {
    if (!this.props.loaded) {
      return <div>Loading...</div>
    }
    return (
      <div>Map will go here</div>
    )
  }
}

export default GoogleApiComponent({
  apiKey: __GAPI_KEY__
})(Container)
```

**Comment by wedneyyuri** [comment]
It's also on README: https://github.com/fullstackreact/google-maps-react#automatically-lazy-loading-google-api
>
>## Automatically Lazy-loading Google API
>
>The library includes a helper to wrap around the Google maps API. The `GoogleApiWrapper` Higher-Order component accepts a configuration object which *must* include an `apiKey`. See [lib/GoogleApi.js](https://github.com/fullstackreact/google-maps-react/blob/master/src/lib/GoogleApi.js#L4) for all >options it accepts.
>
>```javascript
>import {GoogleApiWrapper} from 'GoogleMapsReactComponent'
>
>// ...
>
>export class Container extends React.Component {}
>
>export default GoogleApiWrapper({
>  apiKey: __GAPI_KEY__
>})(Container)
>```
>
>The `GoogleApiWrapper` automatically passes the `google` instance loaded when the component mounts (and will only load it once).
>
>## Manually loading the Google API
>
>If you prefer not to use the automatic loading option, you can also pass the `window.google` instance as a `prop` to your `<Map />` component.

**Comment by andy-pro** [comment]
Look at [here](https://github.com/fullstackreact/google-maps-react/issues/24#issuecomment-312487925)
