### ISSUE TITLE
Isomorphic App Error

### ISSUE THREAD

**Issue by jkopelioff** [fullstackreact/google-maps-react#7]
Can anyone suggest a way to make this work for Isomorphic applications?

`error given was: ReferenceError: window is not defined
[1]     at /Users/xxxx/Develop/autogravity-web-app/node_modules/google-maps-react/dist/lib/ScriptCache.js:20:21
[1]     at Object.defineProperty.value (/Users/xxxx/Develop/autogravity-web-app/node_modules/google-maps-react/dist/
lib/ScriptCache.js:5:9)
[1]     at Object.<anonymous> (/Users/xxxx/Develop/autogravity-web-app/node_modules/google-maps-react/dist/lib/Scrip
tCache.js:13:3)`

**Comment by auser** [comment]
Ah, @jkopelioff that's because the `ScriptCache.js` library requires the `window` object currently. We can update that by removing that dependency. That's a great idea.

**Comment by pnmsharma** [comment]
Hello , I am getting same error ,Please fix this issue soon.

**Comment by auser** [comment]
@jkopelioff and @pnmsharma Can you try from the master branch? I pushed an update to the `ScriptCache.js` and want to make sure it works for you before I cut a new npm module.

**Comment by auser** [comment]
^^ bump?

**Comment by varmais** [comment]
@auser where did you push the update? I can't see anything here: https://github.com/fullstackreact/google-maps-react/commits/master/src/lib/ScriptCache.js :(

**Comment by ryan119** [comment]
@auser me either got this problem , please help.......

**Comment by auser** [comment]
Ah missed this. I'm traveling (U.K. Now), but will look when I get a chance. Hopefully this weekend

**Comment by terenzeyuen** [comment]
Any updates? 👍

**Comment by dtipson** [comment]
When I use this, it deletes the window.google property on window whenever it's called a second time (like when map is destroyed and then recalled: there's no google anymore).

**Comment by 7s4r** [comment]
I made a little workaround for node env. It works for me in isomorphic app. But not sure that it is the best solution. You can check my [PR](https://github.com/fullstackreact/google-maps-react/pull/65).

**Comment by lardissone** [comment]
Any progress on this?

**Comment by kcode20** [comment]
@auser: Is @7s4r 's Pull Request going to be merged in? I have an isomorphic application that still experiences this issue...

**Comment by auser** [comment]
Merged and pushed a new version to `npm`

**Comment by craigtaub** [comment]
@auser sorry but this fix does not appear to be in `npm`.
