### ISSUE TITLE
All evtnames are not showing up in google-maps-react@1.0.18 or google-maps-react@1.0.19

### ISSUE THREAD

**Issue by roshantarudkar** [fullstackreact/google-maps-react#93]
i dont see these events from center_changed onwards in google-maps-react@1.0.18 or google-maps-react@1.0.19..but i do see them in master in this repo..is latest master published or am i missing somthing?

const evtNames = [
  'ready',
  'click',
  'dragend',
  'recenter',
  **'bounds_changed',
  'center_changed',
  'dblclick',
  'dragstart',
  'heading_change',
  'idle',
  'maptypeid_changed',
  'mousemove',
  'mouseout',
  'mouseover',
  'projection_changed',
  'resize',
  'rightclick',
  'tilesloaded',
  'tilt_changed',
  'zoom_changed'**
];

**Comment by auser** [comment]
Try grabbing the latest `v1.1.0`.
