### ISSUE TITLE
cannot resolve module utils/cache and utils/GoogleApi

### ISSUE THREAD

**Issue by nxmohamad** [fullstackreact/google-maps-react#97]
putting this here as reference as it's presently not in any of the issues.

If you are following the tutorial and wondering why there is an import statement to a folder that doesn't exist based on the tutorials.. welcome.

I was confused until I realised the patter in the names. utils/cache refers to ScriptCache and utils/GoogeApi refers to GoogleApi

Just change the import location and filename and it will work!

**Comment by auser** [comment]
Thanks for the note. Feel free to make a PR to add to the README.
