### ISSUE TITLE
multiple google maps on one page

### ISSUE THREAD

**Issue by calasteo** [fullstackreact/google-maps-react#98]
hello, 
i use this libary to make multiple google map for each city (in my data);
the first google map can be centered by initialCenter props, unfortunatelly 2nd maps, 3rd ... etc automaticly centered by first google map,  here is my code

import React from 'react'
import Map, {Marker} from 'google-maps-react'

const SimpleMap = (props) => {
    return (
        <Map containerStyle={{width: '400px', height: '200px'}} google={props.google}
             initialCenter={{
                 lat: props.lat,
                 lng: props.lng
             }}
             style={{width: '100%', height: '100%', position: 'relative'}}
             className={'map'}
             zoom={12}>
            <Marker
                name={'Location'}
                position={{lat: props.lat, lng: props.lng}}/>
        </Map>
    )
};

export default SimpleMap;

anyone can help ? btw sorry for bad English

**Comment by Edgargmc** [comment]
same error. "You have included the Google Maps API multiple times on this page. This may cause unexpected errors."
